### ISSUE TITLE
Configure

### ISSUE THREAD

**Issue by nicosampler** [1beb/ui-too-small#2]
how can configure the menu size?
on rename, the filename is half.

thanks. very useful addon!

**Comment by 1beb** [comment]
You can make your own adjustments by editing main.js in your user extension folder. 

Help > Show Extensions Folder > Navigate to user > Navigate to ui too small > open main.js, review css and edit as you need to. 

You'll find this file, https://github.com/1beb/ui-too-small/blob/master/main.js you can edit to your hearts content. Recommend changing the folder name so you avoid having your changes overwritten with future updates to the extension.
