### ISSUE TITLE
File rename box small and unreadable.

### ISSUE THREAD

**Issue by savbran** [1beb/ui-too-small#3]
Hi, sorry to bother with this issue but I don't know how to ask support for this exstension.

I explain the problem:
- I set in the main.js file a new size for my ui 
- The ui is updated with the new bigger size :) 
- Now if I rename a file, opening the context menu-> rename function, clicking with right mouse button on the file tree view left panel of brackets window, the editing box that appears is too small in reading the file name to change.

Can you verify? Is there any setting to enlarge also the editing box of rename ?  Many thanks for the info you can provide.

**Comment by 1beb** [comment]
I think someone forked it to deal specifically with a similar problem. https://github.com/mgspross/brackets-hidpi-support
